version: '3.9'
services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: rest-api-with-spring
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - gil-network
  rest-api-with-spring:
    image: gilmarbnp/rest-api-with-spring
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest-api-with-spring?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - gil-network
networks:
  gil-network:
    driver: bridge
