server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
file:
  upload-dir: /home/runner/work/spring-aws-docker-project/Upload_api_springaws
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rest_api_with_spring?useTimezone=true&serverTimezone=UTC
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 150MB
      max-request-size: 100MB  
springdoc:
  pathsToMatch: /api/**/**
  swagger-ui:
    use-root-path: true