name: Continuos Integration With GitHub Actions

on:
  push:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven

    - name: Print Current Directory
      run: pwd

    - name: Create upload directory
      run: mkdir -p /home/runner/work/spring-aws-docker-project/Upload_api_springaws

    - name: Build Application JAR
      working-directory: .
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./spring-aws-docker-project
      run: docker-compose build
       

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-api-with-spring:latest ${{ secrets.DOCKER_USERNAME }}/rest-api-with-spring:${{ github.run_id }}
       
        docker push  ${{ secrets.DOCKER_USERNAME }}/rest-api-with-spring:${{ github.run_id }}
        docker push  ${{ secrets.DOCKER_USERNAME }}/rest-api-with-spring:latest
